services:
  runtime:
    image: nd_docker-runtime:local
    build:
      context: ./runtime
      dockerfile: Dockerfile
      target: runtime

  shiny:
    image: nd_docker-shiny_serve:local
    build:
      context: ./runtime
      dockerfile: Dockerfile
      target: shiny

  static:
    image: nd_docker-static_serve:local
    build:
      context: ./runtime
      dockerfile: Dockerfile
      target: static
