services:
  quarto_render:
    container_name: static_render
    image: static_render:latest
    build:
      context: .
      dockerfile: static_render.Dockerfile
    pull_policy: never
    working_dir: /nd.site
    volumes:
      - /home/rackelhahn69/Documents/endikau/nd.site:/nd.site
    command: |
      sleep 1000h
      
    # R -e "source('setup.R')"
    # quarto render
