name: Build and publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image 1
        uses: docker/build-push-action@v5
        with:
          file: static_render.Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nd_docker-static_render:latest

      - name: Build and push image 2
        uses: docker/build-push-action@v5
        with:
          file: shiny_serve.Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nd_docker-shiny_serve:latest

